const envDev = {
  campusvirtual_token: "CAMPUS_VIRTUAL_TOKEN",
  campusvirtual_refresh: "CAMPUS_VIRTUAL_REFRESH",
  host: "", //'http://localhost:3003',
  checkAuth: "http://localhost:3003/checkAuthorization",
  refreshToken: "http://localhost:3003/refreshToken",
  redirectLogin: "http://localhost:3031/auth/azureadoauth2",
  getAccountStatus: "http://localhost:3003/accountService/api/account",
  getDashboard: "http://localhost:3003/dashboard/v2",
  privacyNotice: "http://localhost:3003/privacyNotice",
  getBankDeposit: "http://localhost:3003/paymentService/api/bankdeposit",
  invoices: "http://localhost:3003/invoicingService/api",
  deleteInvoice: "http://localhost:3003//invoicingService/api/delete",
  taxRegime: "http://localhost:3003/invoicingService/api/taxRegime",
  saveInvoice:
    "http://localhost:3003/invoicingService/api/invoicingPreferences",
  getMercadoPago: "http://localhost:3003/paymentService/api/mercadopago",
  getConcepts: "http://localhost:3003/paymentService/api/transactions",
  deleteConcept: "http://localhost:3003/paymentService/api/cancelTransactions",
  getAccountReport: "http://localhost:3003/paymentService/api/bankdeposit",
  logout:
    "https://login.microsoftonline.com/494e1e35-2749-4073-8510-1d3a64d05810/oauth2/logout?post_logout_redirect_uri=https://app-cv-oauth-dev.azurewebsites.net/auth/azureadoauth2/callback",
  getZip: "http://localhost:3003/api/v1/zip-codes",
  redirectLibrary: "https://kohateca.ula.edu.mx",
  redirectClassroom: "https://aula.ula.edu.mx",
  videoPayment:
    "https://cdnapisec.kaltura.com/html5/html5lib/v2.96.2/mwEmbedFrame.php/p/2789311/uiconf_id/45634311/entry_id/1_ndjmhffa?wid=_2789311&iframeembed=true&playerId=kaltura_player_1657135885&entry_id=1_ndjmhffa",
  getDebitPeriods: "http://localhost:3003/accountService/api/debitPeriods",
  getAccountMovements: "http://localhost:3003/accountService/api/period",
  getPrograms: "http://localhost:3003/accountService/api/account/programs",
  studyRecord: "http://localhost:3003/schoolServices/api/proofOfStudy/v1",
  academicHistory: "http://localhost:3003/schoolServices/api/academicRecord/v1",
  certificateStudy:
    "http://localhost:3003/schoolServices/api/studyCertificate/v1",
  equivalenceStudies:
    "http://localhost:3003/schoolServices-ces/api/equivalencyOfStudies/v1",
  redirectLoginHome: "https://twitter.com/explore",
  getKeyMoodle: "http://localhost:3003/api/v1/moodleRegisterId",
  moodleRedirect: "https://moodledev.ula.edu.mx/ssomoodlespacio/utcsso.php",
  headerId: "Ocp-Apim-Subscription-Key",
  contentStatic: "https://campusvirtual.azureedge.net/public/assets/texts/utc",
  contentAssets: "https://campusvirtual.azureedge.net/public/assets/",
  contentAssetsMark:
    "https://campusvirtual.azureedge.net/public/assets/images/utc/",
  mark: "utc",
  credential: "http://localhost:3003/schoolServices-ces/api/credential/v1",
  requestInquiry:
    "http://localhost:3003/schoolServices-ces/api/requestAllProcedures/v1",
  proceduresCosts: "http://localhost:3003/paymentService/api/formalities",
  reinstatement:
    "http://localhost:3003/schoolServices-ces/api/reinstatement/v1",
  degree: "http://localhost:3003/schoolServices-ces/api/degree/v1",
  academicHelp: "http://localhost:3003/helpCenterService/api/academicHelp/v1",
  financialHelp: "http://localhost:3003/helpCenterService/api/financialHelp/v1",
  proceduresHelp:
    "http://localhost:3003/helpCenterService/api/proceduresAndServices/v1",
  technicalHelp: "http://localhost:3003/helpCenterService/api/technicalHelp/v1",
  faqsHelp: "http://localhost:3003/helpCenterService/api/faqs",
  dashboardHelp: "http://localhost:3003/helpCenterService/api/dashboard",
  logsErrors: "http://localhost:3003/logService/api/logErrors/v1",
  searchHelpCenter: "http://localhost:3003/helpCenterService/api/search/v1",
  redirectCurp: "https://www.gob.mx/curp/",
  getTicketsHelpCenter:
    "http://localhost:3003/helpCenterService/api/GetRequestTickets/v1",
  getSocialServiceProcedure:
    "http://localhost:3003/schoolServices/api/socialService/v1",
  postCreditCard: "http://localhost:3003/paymentService/api/stripeAddCard",
  deleteCreditCard: "http://localhost:3003/paymentService/api/stripeDeleteCard",
  stripePayment: "http://localhost:3003/paymentService/api/stripePayment",
  getCreditCards: "http://localhost:3003/paymentService/api/stripeGetCard",
  getDirectoryHelp: "http://localhost:3003/helpCenterService/api/directory/v1",
  getBenefits: "http://localhost:3003/api/v1/benefits",
  publicKeyStripe:
    "pk_test_51KGqgdF5JHugNzfeX4113UW4hY6Ni5TrFN8ZHunBD0ZOSAurJLwHLlRxXnjieln8uW0yt8ca3458VfbkqJIHHXqY00TSGeLWfv",
  clientStripe: "pi_3KnVi0F5JHugNzfe0rpUTDDj_secret_fWdzkASq4eEqjzNjZbioDCdAN",
  calendar: "http://localhost:3003/schoolServices/api/calendarsFiles/v1",
  psyschologicalHelp: "https://micap.utc.mx/",
  invoiceLink: "https://www.gob.mx/curp/",
  scholarship: "http://localhost:3003/schoolServices/api/v1/scholarship",
  revalidateStudies:
    "http://localhost:3003/schoolServices-ces/api/reinstatement/v1",
  reviewAcademicHistory:
    "http://www3.ula.edu.mx/Servicios_Web_ULA/Historia_Academica/Hist-Aca.aspx",
  postSearchAmount: "http://localhost:3003/paymentService/api/searchAmount",
  programChange: "http://localhost:3003/schoolServices/api/v1/programChange",
  admissionCertificate:
    "http://localhost:3003/schoolServices/api/v1/admissionCertificate",
  sedeOnline: "www3.ula.edu.mx/portal_documentos",
  sedeEscolarizado: "https://alumnos.ula.edu.mx/portal_documentos/",
  violettaLink: "https://wa.link/zlv5fh",
  manhattanCourses: "http://localhost:3003/manhattan/api/v1/courses",
  manhattanEnrollment: "http://localhost:3003/manhattan/api/v1/enrollment",
};

const envNode = {
  campusvirtual_token: process.env.REACT_APP_CAMPUS_VIRTUAL_TOKEN,
  campusvirtual_refresh: process.env.REACT_APP_CAMPUS_VIRTUAL_REFRESH,
  host: "",
  checkAuth: process.env.REACT_APP_CHECK_AUTH,
  refreshToken: process.env.REACT_APP_REFRESH_AUTH,
  redirectLogin: process.env.REACT_APP_REDIRECT_LOGIN,
  getAccountStatus: process.env.REACT_APP_GET_ACCOUNT_STATUS,
  getDashboard: process.env.REACT_APP_GET_DASHBOARD,
  privacyNotice: process.env.REACT_APP_PRIVACY_NOTICE,
  getBankDeposit: process.env.REACT_APP_GET_BANK_DEPOSIT,
  invoices: process.env.REACT_APP_INVOICES,
  deleteInvoice: process.env.REACT_APP_DELETE_INVOICE,
  taxRegime: process.env.REACT_APP_TAX_REGIME,
  saveInvoice: process.env.REACT_APP_SAVE_INVOICE,
  getMercadoPago: process.env.REACT_APP_GET_MERCADO_PAGO,
  getConcepts: process.env.REACT_APP_GET_CONCEPTS,
  deleteConcept: process.env.REACT_APP_DELETE_CONCEPT,
  getAccountReport: process.env.REACT_APP_GET_ACCOUNT_REPORT,
  logout: process.env.REACT_APP_LOGOUT,
  getZip: process.env.REACT_APP_ZIP,
  redirectLibrary: process.env.REACT_APP_REDIRECT_LIBRARY,
  redirectClassroom: process.env.REACT_APP_REDIRECT_CLASSROOM,
  videoPayment: process.env.REACT_APP_VIDEO_PAYMENT,
  getDebitPeriods: process.env.REACT_APP_DEBIT_PERIODS,
  getAccountMovements: process.env.REACT_APP_ACCOUNT_MOVEMENTS,
  getPrograms: process.env.REACT_APP_PROGRAMS,
  studyRecord: process.env.REACT_APP_STUDY_RECORD,
  academicHistory: process.env.REACT_APP_ACADEMIC_HISTORY,
  certificateStudy: process.env.REACT_APP_CERTIFICATE_STUDY,
  equivalenceStudies: process.env.REACT_APP_EQUIVALENCE_STUDIES,
  redirectLoginHome: process.env.REACT_APP_REDIRECT_LOGIN_HOME,
  getKeyMoodle: process.env.REACT_APP_MOODLE_KEY,
  moodleRedirect: process.env.REACT_APP_REDIRECT_MOODLE,
  headerId: process.env.REACT_APP_HEADER_ID,
  contentStatic: process.env.REACT_APP_CONTENT_STATIC,
  contentAssets: process.env.REACT_APP_CONTENT_ASSETS,
  contentAssetsMark: process.env.REACT_APP_CONTENT_ASSETS_MARK,
  mark: process.env.REACT_APP_MARK,
  requestInquiry: process.env.REACT_APP_REQUEST_INQUIRY,
  proceduresCosts: process.env.REACT_APP_PROCEDURES_COSTS,
  reinstatement: process.env.REACT_APP_REINSTATEMENT,
  degree: process.env.REACT_APP_DEGREE,
  academicHelp: process.env.REACT_APP_ACADEMIC_HELP,
  financialHelp: process.env.REACT_APP_FINANCIAL_HELP,
  proceduresHelp: process.env.REACT_APP_PROCEDURES_HELP,
  technicalHelp: process.env.REACT_APP_TECHNICAL_HELP,
  faqsHelp: process.env.REACT_APP_FAQS_HELP,
  dashboardHelp: process.env.REACT_APP_DASHBOARD_HELP,
  logsErrors: process.env.REACT_APP_LOGS_ERRORS,
  postCreditCard: process.env.REACT_APP_POST_CREDIT,
  deleteCreditCard: process.env.REACT_APP_DELETE_CREDIT,
  getCreditCards: process.env.REACT_APP_GET_CREDIT_CARDS,
  stripePayment: process.env.REACT_APP_STRIPE_PAYMENT,
  publicKeyStripe: process.env.REACT_APP_PUBLIC_KEY_STRIPE,
  clientStripe: process.env.REACT_APP_CLIENT_STRIPE,
  searchHelpCenter: process.env.REACT_APP_SEARCH_HELP_CENTER,
  redirectCurp: process.env.REACT_APP_REDIRECT_CURP,
  getTicketsHelpCenter: process.env.REACT_APP_GET_TICKET_HELP_CENTER,
  getSocialServiceProcedure: process.env.REACT_APP_SOCIAL_SERVICE,
  getBenefits: process.env.REACT_APP_GET_BENEFITS,
  calendar: process.env.REACT_APP_CALENDAR,
  getDirectoryHelp: process.env.REACT_APP_GET_DIRECTORY_HELP,
  psyschologicalHelp: process.env.REACT_APP_PSYSCHOLOGICAL_HELP,
  invoiceLink: process.env.REACT_APP_INVOICE_LINK,
  scholarship: process.env.REACT_APP_SCHOLARSHIP,
  revalidateStudies: process.env.REACT_APP_REVALIDATE_STUDIES,
  reviewAcademicHistory: process.env.REACT_APP_REVIEW_ACADEMIC_HISTORY,
  postSearchAmount: process.env.REACT_APP_POST_SEARCH_AMOUNT,
  programChange: process.env.REACT_APP_PROGRAM_CHANGE,
  admissionCertificate: process.env.REACT_APP_ADMISSION_CERTIFICATE,
  sedeOnline: process.env.REACT_APP_SEDE_ONLINE,
  sedeEscolarizado: process.env.REACT_APP_SEDE_ESCOLARIZADO,
  violettaLink: process.env.REACT_APP_VIOLETTA_LINK,
  manhattanCourses: process.env.REACT_APP_GET_COURSES,
  manhattanEnrollment: process.env.REACT_APP_POST_ENROLLMENT,
};
const env = {
  ...envDev,
};

export default env;
