export const types = {
  paymentGetConcepts: "[Payment] Get Concetps",
  paymentSetTotalPayable: "[Payment] Set Total Payable",
  paymentPostConcept: "[Payment] Post Concept",
  paymentSetConcept: "[Payment] Set Concept",
  paymentGetInvoices: "[Payment] Get Invoices",
  paymentSetInvoice: "[Payment] Set Invoice",
  paymentSetIsInvoice: "[Payment] Set Is Invoice",
  paymentGetMethods: "[Payment] Get Payment",
  paymentSetMethod: "[Payment] Set Method",
  paymentSearchAmount: "[Payment]: Search Amount",
  paymentError: "[Payment] Payment Error",
  paymentReset: "[Payment] Payment Reset",
  paymentEditForm: "[Payment] Payment Edit Form",
  paymentErrors: "[Payment] Errors",
  paymentPathExit: "[Payment] Path Exit",
  paymentSetCards: "[Payment] Set Cards",
  paymentGetDownload: "[Payment] Get Download",
  paymentSetCardId: "[Payment] Set Card Id",
  paymentCreditCard: "[Payment] Credit Card",
  paymentStripe: "[Payment] Stripe Payment",
  paymentTaxRegime: "[Payment] Tax Regime",
  termsAndPrivacyGetStatus: "[TermsAndPrivacy] Get Terms and Privacy",
  termsPatchStatus: "[TermsAndPrivacy] Patch Terms",
  termsReset: "[TermsAndPrivacy] Reset",
  privacyPatchStatus: "[TermsAndPrivacy] Patch Privacy",
  termsErrors: "[TermsAndPrivacy] Error",
  dashboardGetData: "[Dashboard] Get Data",
  loadingShow: "[Loading] Show Loading",
  dashboardErrors: "[Dashboard] Errors",
  dashboardLoading: "[Dashboard] Loading",
  headersSetAuth: "[Headers] Set Auth",
  accountStatusSetProfile: "[AccountStatus] Set Profile",
  accountStatusReset: "[AccountStatus] Reset",
  splashShow: "[Splash] Show Splash",
  accountStatusError: "[AccountStatus] Errors",
  loginSetTokens: "[Login] Set Access and Refresh Token",
  accountStatusSuccess: "[AccountStatus] Success",
  getZip: "[Payment] Get Zip",
  zipErrors: "[Payment] Errors",
  accountStatussSetDebitPeriod: "[AccountStatus] Set Debit Period",
  accountMovements: "[AccountStatus] Account Movements",
  accountStatusPrograms: "[AccountStatus] Get Programs",
  paymentConceptDefault: "[Payment] Select Concept Default",
  procedureStudyRecordInfo: "[Procedure] Study Record Information",
  procedureStudyRecordDoc: "[Procedure] Study Record Documentaition",
  procedureStudyRecordModal: "[Procedure] Study Record Info Modal",
  procedureStudyRecordData: "[Procedure] Study Record Data",
  procedureAcademicHistoryInfo: "[Procedure] Academic History Information",
  procedureAcademicHistoryDoc: "[Procedure] Academic History Documentation",
  procedureCertificateStudyInfo: "[Procedure] Certificate Study Information",
  procedureCertificateStudyDoc: "[Procedure] Certificate Study Documentation",
  procedureCertificateStudyData: "[Procedure] Certificate Study Data",
  procedureCertificateStudyReset: "[Procedure] Certificate Study Reset",
  procedureEquivalenceStudiesInfo:
    "[Procedure] Equivalence Studies Information",
  procedureEquivalenceStudiesDoc:
    "[Procedure] Equivalence Studies Documentation",
  procedureEquivalenceStudiesReset: "[Procedure] Equivalence Studies Reset",
  procedureEquivalenceStudiesData: "[Procedure] Equivalence Studies Data",
  procedureEquivalenceStudiesError: "[Procedure] Equivalence Studies Error",
  procedureAcademicHistoryData: "[Procedure] Academic History Data",
  procedureAcademicHistoryReset: "[Procedure] Academic History Reset",
  procedureAcademicHistoryError: "[Procedure] Academic History Error",
  procedureRevalidateStudiesInfo: "[Procedure] Revalidate Studies Information",
  procedureRevalidateStudiesDoc: "[Procedure] Revalidate Studies Documentation",
  procedureRevalidateStudiesReset: "[Procedure] Revalidate Studies Reset",
  procedureRevalidateStudiesOneData: "[Procedure] Revalidate Studies Data One",
  procedureRevalidateStudiesTwoData: "[Procedure] Revalidate Studies Data Two",
  procedureRevalidateStudiesError: "[Procedure] Revalidate Studies Error",
  procedureStudyRecordReset: "[Procedure] Study Record Reset",
  textsSetValues: "[Texts] Set Values",
  procedureCredentialInfo: "[Procedure] Credential Information",
  procedureCredentialDoc: "[Procedure] Credential Documentation",
  procedureCredentialData: "[Procedure] Credential Data",
  procedureCredentialReset: "[Procedure] Credential Reset",
  proceduresSetRequestInquiry: "[Procedures] Set Request Inquiry",
  proceduresSetAll: "[Procedures] Set All Procedures",
  proceduresReset: "[Procedures] Reset Procedures",
  proceduresSetProfile: "[Procedures] set Profile",
  procedureReinstatementInfo: "[Procedure] Reinstatement Information",
  procedureReinstatementData: "[Procedure] Reinstatement Data",
  procedureReinstatementReset: "[Procedure] Reinstatement Reset",
  procedureDegreeOnlineInfo: "[Procedure] Degree Online Information",
  procedureDegreeGraduateInfo: "[Procedure] Degree Graduate Information",
  procedureDegreeDoc: "[Procedure] Degree Documentation",
  procedureDegreeOnlineData: "[Procedure] Degree Online Data",
  procedureDegreeGraduateData: "[Procedure] Degree Graduate Data",
  procedureDegreeModalOnline: "[Procedure] Degree Modal Online",
  procedureDegreeModalGraduate: "[Procedure] Degree Modal Graduate",
  procedureDegreeSetData: "[Procedure] Degree Set Data",
  procedureDegreeReset: "[Procedure] Degree Reset",
  procedureDegreeSetTypeId: "[Procedure] Degree Set Type Id",
  procedureDegreeError: "[Procedure] Degree Error",
  procedureScholarshipInfo: "[Procedure] Scholarship Information",
  procedureScholarshipRenovationType:
    "[Procedure] Scholarship Set Renovation Type",
  procedureScholarshipData: "[Procedure] Scholarship Data",
  procedureScholarshipReset: "[Procedure] Scholarship Reset",
  procedureScholarshipError: "[Procedure] Scholarship Error",
  procedureAdmissionCertificateInfo:
    "[Procedure] Admission Certificate Information",
  procedureAdmissionCertificateData: "[Procedure] Admission Certificate Data",
  procedureAdmissionCertificateDoc:
    "[Procedure] Admission Certificate Documents",
  procedureAdmissionCertificateReset: "[Procedure] Admission Certificate Reset",
  proceduresErrors: "[Procedures] Errors",
  proceduresPathExit: "[Procedures] Path Exit",
  proceduresStudyRecordExtra: "[Procedures] Study Record Extra",
  procedureCertificateStudyExtra: "[Procedures] Certificate Study Extra",
  procedureSocialServiceData: "[Procedures] Social Service Data",
  procedureSocialServiceError: "[Procedures] Social Service Error",
  procedureSocialServiceReset: "[Procedures] Social Service Reset",
  procedureSocialServiceInfo: "[Procedures] Social Service Information",
  procedureSocialServiceTypeId: "[Procedures] Social Service typeId",
  procedureProgramChangeInfo: "[Procedure] Program Change Information",
  procedureProgramChangeData: "[Procedure] Program Change Data",
  procedureProgramChangeReset: "[Procedure] Program Change Reset",
  procedureProgramChangeError: "[Procedure] Program Change Error",
  procedureCalendarSetOption: "[Procedure] Calendar Set Option",
  helpCenterAcademicInfo: "[Help Center] Academic  Information",
  helpCenterAcademicData: "[Help Center] Academic  Data",
  helpCenterAcademicDoc: "[Help Center] Academic  Documents",
  helpCenterAcademicTickets: "[Help Center] Academic Tickets",
  helpCenterAcademicRecordType: "[Help Center] Academic RecordType",
  helpCenterAcademicFaqs: "[Help Center] Academic Faqs",
  helpCenterAcademicOptionsAds: "[Help Center] Academic Options Ads",
  helpCenterAcademicReset: "[Help Center] Academic  Reset",
  helpCenterAcademicError: "[Help Center] Academic  Error",
  helpCenterErrors: "[Help Center] Errors",
  helpCenterFinancial: "[Help Center] Financial  Help Center",
  helpCenterFinancialFaqs: "[Help Center] Financial  FAQS",
  helpCenterFinancialTickets: "[Help Center] Financial  Tickets",
  helpCenterFinancialRecordType: "[Help Center] Financial  RecordType",
  helpCenterFinancialInfo: "[Help Center] Financial  Information",
  helpCenterFinancialData: "[Help Center] Financial  Data",
  helpCenterFinancialDoc: "[Help Center] Financial  Documents",
  helpCenterFinancialReset: "[Help Center] Financial  Reset",
  helpCenterFinancialError: "[Help Center] Financial  Error",
  helpCenterFinancialOptionsAds: "[Help Center] Financial  Options Ads",
  helpCenterProcedures: "[Help Center] Procedures  Help Center",
  helpCenterProceduresFaqs: "[Help Center] Procedures  FAQS",
  helpCenterProceduresTickets: "[Help Center] Procedures  Tickets",
  helpCenterProceduresRecordType: "[Help Center] Procedures  RecordType",
  helpCenterProceduresRecordTypeId: "[Help Center] Procedures  RecordTypeId",
  helpCenterProceduresInfo: "[Help Center] Procedures  Information",
  helpCenterProceduresData: "[Help Center] Procedures  Data",
  helpCenterProceduresDoc: "[Help Center] Procedures  Documents",
  helpCenterProceduresReset: "[Help Center] Procedures  Reset",
  helpCenterProceduresError: "[Help Center] Procedures  Error",
  helpCenterTechnical: "[Help Center] Technical  Help Center",
  helpCenterTechnicalFaqs: "[Help Center] Technical  FAQS",
  helpCenterTechnicalTickets: "[Help Center] Technical  Tickets",
  helpCenterTechnicalRecordType: "[Help Center] Technical  RecordType",
  helpCenterTechnicalInfo: "[Help Center] Technical Information",
  helpCenterTechnicalData: "[Help Center] Technical Data",
  helpCenterTechnicalDoc: "[Help Center] Technical Documents",
  helpCenterTechnicalOptionsAds: "[Help Center] Technical Options Ads",
  helpCenterTechnicalReset: "[Help Center] Technical Reset",
  helpCenterTechnicalError: "[Help Center] Technical Error",
  helpCenterDashboardData: "[Help Center] dasbhoard Data",
  helpCenterDashboardError: "[Help Center] dasbhoard Error",
  helpCenterDashboardReset: "[Help Center] dasbhoard Reset",
  helpCenterDashboardRequestAllTickets:
    "[Help Center] dasbhoard request all tickets",
  helpCenterFaqsData: "[Help Center] Faqs Data",
  helpCenterFaqsSearch: "[Help Center] Faqs Search",
  helpCenterFaqsError: "[Help Center] Faqs Error",
  helpCenterFaqsReset: "[Help Center] Faqs Reset",
  benefitsCards: "[Benefits] benefits cards",
  benefitsDetail: "[Benefits] benefits detail",
  benefitsReset: "[Benefits] benefits Reset",
  benefitsError: "[Benefits] benefits Error",
  helpCenterDirectoryData: "[Help Center] Directory Data",
  helpCenterDirectoryError: "[Help Center] Directory Error",
  helpCenterDirectoryReset: "[Help Center] Directory Reset",
  helpCenterDirectoryCoordinators:
    "[Help Center] Directory Coordinators Option",
  helpCenterDirectoryAdvisors: "[Help Center] Directory Advisors Option",
  manhattanSetData: "[Manhattan] Set Data",
  manhattanReload: "[Manhattan] Set Reload",
};
