name: CampusVirtual Dev Pipeline

pool:
  vmImage: ubuntu-latest

trigger: 
  - develop

pr:
  - feature/*
  - bugfix/*

variables:
  - group: npm
  - name: 'GitVersion.SemVer'
    value: ''
  
stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      inputs:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-Container-Registry'
        repository: 'campusvirtual'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(GitVersion.SemVer)'
        arguments: '--build-arg NPM_TOKEN=$(npmToken)'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-Container-Registry'
        repository: 'campusvirtual'
        command: 'push'
        tags: '$(GitVersion.SemVer)'
    
    - bash: |
       echo "##vso[task.setvariable variable=Semver;isOutput=true]$(GitVersion.SemVer)"
      name: SetGitVersion

- stage: Deploy
  jobs:
  - job: 'DeployToAppService'
    variables:
      GitVersion.Semver: $[stageDependencies.Build.BuildAndPush.outputs['SetGitVersion.SemVer']]
    steps:
    - bash: echo semver $(GitVersion.Semver)

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Lottus-Registry-Dev'
        appType: 'webAppContainer'
        WebAppName: 'app-campusvirtual-dev'
        DockerNamespace: 'lottus.azurecr.io'
        DockerRepository: 'campusvirtual'
        DockerImageTag: '$(GitVersion.Semver)'